root: true
env:
  node: true
  browser: true
  es6: true  # includes Float32Array
parserOptions:
  ecmaVersion: 6
  sourceType: 'module'
extends: ['eslint:recommended', 'google']
rules:
  # disable for now, until it's more flexible
  indent: [0, 2, {SwitchCase: 1, outerIIFEBody: 0,
                  ArrayExpression: 'first',
                  ObjectExpression: 'first',
                  CallExpression: {arguments: 'first'},
                  FunctionDeclaration: {parameters: 'first'},
                  FunctionExpression: {parameters: 'first'} }]
  brace-style: [2, '1tbs', {'allowSingleLine': true}]
  space-before-function-paren: [2, {'anonymous': 'always', 'named': 'never'}]
  curly: [2, 'multi-line', 'consistent']
  spaced-comment: 0  # comments are spaced, but not commented out code
  object-curly-spacing: 0
  operator-linebreak: [2, 'after', {'overrides': {':': 'ignore'}}]
  camelcase: 0
  linebreak-style: 0  # \r\n is ok in a working copy, but not in the repo
  require-jsdoc: 0
  no-console: 0
  #prefer-const: 1
  prefer-spread: 0
  no-multi-spaces: [2, {ignoreEOLComments: true }]
