root: true
env:
  node: true
  browser: true
extends: 'xo'
rules:
  max-len: [2, 80, {'ignoreComments': true, 'ignoreUrls': true}]
  indent: [1, 2, {'SwitchCase': 1, 'outerIIFEBody': 0}]
  # relaxing rules
  brace-style: [2, '1tbs', {'allowSingleLine': true}]
  max-statements-per-line: [2, {'max': 2}] # sometimes 2 is ok
  curly: [2, 'multi-line', 'consistent']
  spaced-comment: 0  # comments are spaced, but not commented out code
  space-infix-ops: 0  # no space is useful for visual grouping
  no-path-concat: 0
  default-case: 0
  one-var: 0
  no-negated-condition: 0
  object-curly-spacing: 0
  no-multiple-empty-lines: [2, {'max': 2}]
  operator-linebreak: [2, 'after', {'overrides': {':': 'ignore'}}]
  camelcase: 0
  no-mixed-operators: 0
  object-property-newline: 0
  no-warning-comments: 0
  max-depth: 0
  max-lines: 0
  no-eq-null: 0
  eqeqeq: [2, 'allow-null']
  linebreak-style: 0  # \r\n is ok in a working copy, but not in the repo
